### ISSUE TITLE
Presently, no underlay mode is implemented, so I'm wondering when this feature will be started? 

### ISSUE THREAD

**Issue by alpha-li** [openvswitch/ovn-kubernetes#105]

**Comment by russellb** [comment]
In the OpenStack case, I see the OpenStack Kuryr project as the way to do it, with OVN as the backend to OpenStack.

Is there are particular use case you're looking for?

I think the entry in the README is probably confusing since it doesn't provide any more info.  It should probably just be removed.

**Comment by alpha-li** [comment]
With the kuryr project actively developed, will the underlay mode be considered in the near future or  is there any plan to do this?
