### ISSUE TITLE
Use kubernetes official python client

### ISSUE THREAD

**Issue by feiskyer** [openvswitch/ovn-kubernetes#111]
There is an official python client of kubernetes at https://github.com/kubernetes-incubator/client-python, which could be easily installed via `pip install kubernetes`.

With python client, it could simplify adding new features (e.g. network policy in #48) and golang library (e.g. #110) is not required for this project.

**Comment by shettyg** [comment]
@feiskyer 

Thanks for bringing it up. We had a discussion around this a few months ago and it was felt that moving to golang library will mean less maintenance headache as we go forward. Few of the reasons were:

1. The guys at openshift have more experience with golang and they felt that golang libraries will always be better maintained than python ones when it comes to kubernetes. 

2. People in the container world are used to golang and it felt like we were going against the norm with Python.

3. It is easier to distribute binaries with golang.

4. Since golang is compilable, we find silly bugs earlier.

The disadvantage was that OVSDB libraries are written in Python and it would have been a lot easier for us to make the watcher much faster if we stick to Python.

**Comment by feiskyer** [comment]
@shettyg Excellent. So what's the plan of migrating this to go?

**Comment by shettyg** [comment]
@feiskyer The first step is to get #110 merged. For a short time, there will be 2 watchers. As and when go watcher has all the features that python watcher has, we remove python watcher. Eventually, we remove all the python utilities too.

**Comment by feiskyer** [comment]
@shettyg Thanks. Looking forward to it.
