### ISSUE TITLE
Vagrant sample service is not working

### ISSUE THREAD

**Issue by gopinatht** [openvswitch/ovn-kubernetes#164]
I followed the instructions https://github.com/openvswitch/ovn-kubernetes/tree/master/vagrant

I am able to see the pods and services:

```
root@k8smaster:~# k get pods
NAME         READY     STATUS    RESTARTS   AGE
apachetwin   1/1       Running   0          50s
nginxtwin    1/1       Running   0          43s
root@k8smaster:~# k get svc
NAME             CLUSTER-IP        EXTERNAL-IP   PORT(S)          AGE
apacheexternal   192.168.200.252   <nodes>       8800:31269/TCP   10s
apacheservice    192.168.200.98    <none>        8800/TCP         21s
kubernetes       192.168.200.1     <none>        443/TCP          3h
```
But doing `curl 10.10.0.11:31269` does not work.

```
root@k8smaster:~# curl 10.10.0.11:31269
curl: (7) Failed to connect to 10.10.0.11 port 31269: Connection refused
```

I even tried to SSHing into a pod and using the service IP. But it only works half the time (with the NGINX pod). It does not work when it balances to the the APACHE pod:

```
[root@apachetwin /]# curl 192.168.200.252:8800
^C
[root@apachetwin /]#
```

**Comment by shettyg** [comment]
@gopinatht 

Couple of things.

1. Can you try accessing  10.10.0.11:31269 from outside of your cluster (say from your host and not from VMs).  Since in the vagrant we share the same IP for mgmt as well as data, access of it from inside the cluster does not work.

2. In your case of sshing into "apachetwin" and accessing curl 192.168.200.252:8800, you are effectively asking to loadbalance back to yourself, which won't work. You can create
a) Try to access 'curl 192.168.200.252:8800' from a k8s-master (or other VMs). Try to access 'curl 192.168.200.98:8800' from the VMs too.
b) Create a new pod (unrelated to the service) and try to access 'curl 192.168.200.98:8800' from it.

**Comment by gopinatht** [comment]
@shettyg Many thanks for the explanation. Both your scenarios (from host and service IP from VM) work. 

We can close this case.

I am interested in understanding how the kubernetes service IP is accessible from the VM. Is there any documentation around this? Also, why are the Pods not able to reach the internet? How can I program the switch to allow access to internet for the pods?

**Comment by shettyg** [comment]
>I am interested in understanding how the kubernetes service IP is accessible from the VM.

When we initialize the setup by running, "ovn-k8s-overlay master-init" or "ovn-k8s-overlay minion-init", we create a OVS interface on that VM which and give it a IP address. For e.g., If you run
```
 ovn-k8s-overlay master-init \
  --cluster-ip-subnet="192.168.0.0/16" \
  --master-switch-subnet="192.168.1.0/24" \
  --node-name="kube-master"
```

We create a OVS device (a logical switch port in the virtual world) on "kube-master" with IP 192.168.1.2/24 and add a routing entry on host that says 192.168.0.0/16 is reachable from 192.168.1.2/24 via 192.168.1.1. That is how you can access service IPs from inside the nodes.

>Also, why are the Pods not able to reach the internet?

That is because in the vagrant, the interface via which we add nodeport is not connected to the internet. It is private. If you create the same setup in real world where the interface that we provide for OVN gateways in 'ovn-k8s-overlay gateway-init' (on which we program nodeport) has reachability for outside internet, it will automatically work.
