### ISSUE TITLE
ovnkube (non master) stops when the node annotation is missing

### ISSUE THREAD

**Issue by pecameron** [openvswitch/ovn-kubernetes#378]
ovnkube should poll until the annotation is present and then start.
Note go-controller/pkg/cluster/node.go does loop poling every second, however the poll hangs after 3 seconds and the Failed to get node/node-annotation message is not displayed.  When the annotation is set it doesn't startup (requires a pod delete).

**Comment by shettyg** [comment]
This looks odd. I don't understand why the poll is hanging. May be the k8s-apiserver or etcd is not setup properly?

**Comment by mihail-velikov** [comment]
I have had this exact problem when there are no nodes where a pod can be scheduled (for example nodes are dead or not enough resources available). When this happens the annotation for IP/MAC never get added to the pod definition even after a node become available for scheduling. In order to resolve this the pod needs to be deleted then the annotation is added successfully.

**Comment by rajatchopra** [comment]
This is perhaps a bug with the scheduler. The ovn-kube code will not be able to add IP/MAC if we do not know which node it has been scheduled to. And we do check again on any update from the scheduler [here](https://github.com/openvswitch/ovn-kubernetes/blob/master/go-controller/pkg/ovn/ovn.go#L128-L134).

Closing this issue. Perhaps need to chase this in upstream kube. Please re-open if the diagnosis is wrong.
