### ISSUE TITLE
OVN controller cpu hogging

### ISSUE THREAD

**Issue by skolome** [openvswitch/ovn-kubernetes#70]
Greetings,

I have been trying to setup the ovn-kubernetes, for 1 master, 2 minions scenario.
The ovn-controller in the master node is always running at ~99%, causing packet drop even in ping requests to one of the minions.

Sidenote: 2nd minion although started and discovered successfully, cannot ping the master node.

Is the cpu hogging an expected behaviour?

Thank you,

Stavros

**Comment by shettyg** [comment]
It is not an expected behavior. The CPU hogging part is a bug which is likely manifesting because of a misconfiguration. Have you tried the vagrant which comes with this? Makes it easy to setup.

I am also available as #shettyg in #openvswitch IRC channel if you want to live debug.

**Comment by owain-je** [comment]
So I came across this problem , it was because the system-id is set to the same value. 

Check this using:
ovs-vsctl get . open_vswitch external-ids:system-id

 if they are the same you can modify using 

id_file=/etc/openvswitch/system-id.conf
test -e $id_file || uuidgen > $id_file
ovs-vsctl set Open_vSwitch . external_ids:system-id=$(cat $id_file) 

on one of the nodes

**Comment by rajatchopra** [comment]
This will also happen if a virtual switch port is created with a clashing name, and bound to OVS on two different chassis.
